### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by jagibson** [iFixit/hydrate-spf#1]
When I try to run the hydarte-spf with the default example or my own domain I get "ValueError: too many values to unpack".  

```
./.virtualenv/bin/python bin/hydrate-spf 'v=spf1 a mx ~all' ifixit.com
Traceback (most recent call last):
  File "bin/hydrate-spf", line 26, in <module>
    arguments['<record>'], arguments['<domain>']))
  File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 118, in hydrate_record
    hydratedRecords.append(hydrate_mechanism(mechanism, domain))
  File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 63, in hydrate_mechanism
    for (_, (_, domain)) in spf.DNSLookup(value, 'mx'):
ValueError: too many values to unpack
```

When I try to run the test it also fails- it also looks like it's trying to compare the address to some kind of hex format.

```
╰─ ./bin/hydrate-spf test -v
Trying:
    hydrate_mechanism('ip4:66.181.10.77')
Expecting:
    'ip4:66.181.10.77'
ok
Trying:
    hydrate_mechanism('ip4:67.192.241.0/24')
Expecting:
    'ip4:67.192.241.0/24'
ok
Trying:
    hydrate_mechanism('a', 'ifixit.com')
Expecting:
    'ip4:75.101.159.182'
**********************************************************************
File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 27, in hydrate_spf.hydrate_spf.hydrate_mechanism
Failed example:
    hydrate_mechanism('a', 'ifixit.com')
Expected:
    'ip4:75.101.159.182'
Got:
    'ip4:&\x00\x18\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01 ip4:&\x00\x18\x02\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01 ip4:208.80.124.2 ip4:208.80.125.2 ip4:208.80.126.2 ip4:208.80.127.2 ip4:208.94.148.2 ip4:75.101.159.182'
Trying:
    hydrate_mechanism('a', 'microsoft.com')
Expecting:
    'ip4:134.170.188.221 ip4:65.55.58.201'
**********************************************************************
File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 31, in hydrate_spf.hydrate_spf.hydrate_mechanism
Failed example:
    hydrate_mechanism('a', 'microsoft.com')
Expected:
    'ip4:134.170.188.221 ip4:65.55.58.201'
Got:
    'ip4:& \x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00S ip4:& \x00\x00\x002\x00\x00\x00\x00\x00\x00\x00\x00\x00S ip4:& \x00\x00\x004\x00\x00\x00\x00\x00\x00\x00\x00\x00S ip4:& \x00\x00\x007\x00\x00\x00\x00\x00\x00\x00\x00\x00S ip4:104.40.211.35 ip4:104.43.195.251 ip4:191.239.213.197 ip4:193.221.113.53 ip4:208.76.45.53 ip4:208.84.0.53 ip4:208.84.2.53 ip4:23.100.122.175 ip4:23.96.52.53'
Trying:
    hydrate_mechanism('mx', 'ifixit.com')
Expecting:
    'ip4:173.203.2.36 ip4:98.129.184.4'
**********************************************************************
File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 35, in hydrate_spf.hydrate_spf.hydrate_mechanism
Failed example:
    hydrate_mechanism('mx', 'ifixit.com')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest hydrate_spf.hydrate_spf.hydrate_mechanism[4]>", line 1, in <module>
        hydrate_mechanism('mx', 'ifixit.com')
      File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 63, in hydrate_mechanism
        for (_, (_, domain)) in spf.DNSLookup(value, 'mx'):
    ValueError: too many values to unpack
Trying:
    hydrate_mechanism('include', 'mailtank.com')
Expecting:
    'ip4:65.50.229.106 ip4:66.181.10.77 ip4:66.181.10.77 ip4:66.181.10.77'
**********************************************************************
File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 40, in hydrate_spf.hydrate_spf.hydrate_mechanism
Failed example:
    hydrate_mechanism('include', 'mailtank.com')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest hydrate_spf.hydrate_spf.hydrate_mechanism[5]>", line 1, in <module>
        hydrate_mechanism('include', 'mailtank.com')
      File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 79, in hydrate_mechanism
        hydrate_record(record, domain=value, fullRecord=False))
      File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 118, in hydrate_record
        hydratedRecords.append(hydrate_mechanism(mechanism, domain))
      File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 63, in hydrate_mechanism
        for (_, (_, domain)) in spf.DNSLookup(value, 'mx'):
    ValueError: too many values to unpack
Trying:
    hydrate_mechanism('include', 'helpscoutemail.com')
Expecting:
    'ip4:23.23.237.213 ip4:74.63.63.121 ip4:74.63.63.115 ip4:54.243.205.80'
**********************************************************************
File "/home/jgibson/git/hydrate-spf/hydrate_spf/hydrate_spf.py", line 44, in hydrate_spf.hydrate_spf.hydrate_mechanism
Failed example:
    hydrate_mechanism('include', 'helpscoutemail.com')
Expected:
    'ip4:23.23.237.213 ip4:74.63.63.121 ip4:74.63.63.115 ip4:54.243.205.80'
Got:
    'ip4:23.23.237.213 ip4:54.173.229.38 ip4:52.0.20.102 ip4:54.174.116.32 ip4:107.23.197.189 ip4:52.2.238.96 ip4:52.20.146.34 ip4:52.1.160.211 ip4:52.5.170.16 ip4:52.4.26.133'
3 items had no tests:
    hydrate_spf.hydrate_spf
    hydrate_spf.hydrate_spf.hydrate_record
    hydrate_spf.hydrate_spf.split_by_length
**********************************************************************
1 items had failures:
   5 of   7 in hydrate_spf.hydrate_spf.hydrate_mechanism
7 tests in 4 items.
2 passed and 5 failed.
***Test Failed*** 5 failures.
```

Running python 2.7.12 on Ubuntu 16.04

**Comment by kwiens** [comment]
Thanks for the report! We're not actively maintaining this tool anymore. If you have a pull request that fixes this issue, we're open to merging it. Or just fork it to make it work for you.

**Comment by scream314** [comment]
@jagibson Lol a _few_ years passed, but I think I fixed this in https://github.com/iFixit/hydrate-spf/pull/2

**Comment by jagibson** [comment]
@scream314 nice!  I ended up rolling my own thing to do this but it's always fun to see an issue that you reported fixed!
